__collection-name__: user-parameter-file

# This collection is used to set the controller for the simulator.

# Jpos_Controller
#file_name : "jpos-user-parameters.yaml"

# Cheetah_Controller
file_name : "new-user-parameters.yaml"
#file_name : "mc-mit-ctrl-user-parameters.yaml"

# Low Level Controller
#file_name : "lowlevel-user-parameters.yaml"

# Spi_Controller
#file_name : "no-parameters.yaml"
